set serveroutput on;

begin execute immediate 'drop index report_xml_idx'; exception when others then null; end;
/
begin execute immediate 'drop table report purge'; exception when others then null; end;
/

create table report(
	report_id number generated by default as identity primary key,
	report_xml xmltype not null
);
/

create or replace procedure generate_warehouse_report_xml(
	p_date_from in date,
	p_date_to in date,
	p_report_xml out xmltype
)
as
begin
	with base as(
		select
			o.order_id,
			o.order_date,
			oi.product_id,
			oi.quantity,
			p.stock_id,
			s.description as stock_description,
			round(oi.quantity*p.price,4) as line_amount
		from orders o
		join order_items oi on oi.order_id=o.order_id
		join products p on p.product_id=oi.product_id
		join stocks s on s.stock_id=p.stock_id
		where o.order_date>=p_date_from
		and o.order_date<p_date_to+1
	),
	stock_totals as(
		select
			b.stock_id,
			max(b.stock_description) as stock_description,
			count(distinct b.order_id) as orders_count,
			sum(b.quantity) as total_quantity,
			round(sum(b.line_amount),4) as total_amount
		from base b
		group by b.stock_id
	)
	select
		xmlelement("report",
			xmlattributes(
				to_char(systimestamp,'yyyy-mm-dd"T"hh24:mi:ss.ff3tzm') as "generated_at",
				to_char(p_date_from,'yyyy-mm-dd') as "date_from",
				to_char(p_date_to,'yyyy-mm-dd') as "date_to"
			),
			(
				select
					xmlelement("summary",
						xmlattributes(
							count(distinct b.order_id) as "total_orders",
							nvl(sum(b.quantity),0) as "total_quantity",
							to_char(
								nvl(sum(b.line_amount),0),
								'FM9999999990D0000',
								'NLS_NUMERIC_CHARACTERS=.,'
							) as "total_amount"
						)
					)
				from base b
			),
			xmlelement("stocks",
				(
					select xmlagg(
						xmlelement("stock",
							xmlattributes(
								st.stock_id as "stock_id",
								st.orders_count as "orders_count",
								st.total_quantity as "total_quantity",
								to_char(
									st.total_amount,
									'FM9999999990D0000',
									'NLS_NUMERIC_CHARACTERS=.,'
								) as "total_amount"
							),
							st.stock_description
						)
					)
					from stock_totals st
				)
			)
		)
	into p_report_xml
	from dual;
end;
/

create or replace procedure insert_warehouse_report(
	p_date_from in date,
	p_date_to in date,
	p_report_id out number
)
as
	v_report_xml xmltype;
begin
	generate_warehouse_report_xml(
		p_date_from=>p_date_from,
		p_date_to=>p_date_to,
		p_report_xml=>v_report_xml
	);

	insert into report(report_xml)
	values(v_report_xml)
	returning report_id into p_report_id;

	commit;
end;
/

create index report_xml_idx
on report(report_xml)
indextype is xdb.xmlindex;
/

create or replace procedure get_report_stock_by_description(
	p_stock_description in nvarchar2
)
as
begin
	for r in(
		select
			rep.report_id,
			x.generated_at,
			x.date_from,
			x.date_to,
			s.stock_id,
			s.orders_count,
			s.total_quantity,
			s.total_amount,
			s.stock_description
		from report rep,
			 xmltable(
				'/report'
				passing rep.report_xml
				columns
					generated_at varchar2(40) path '@generated_at',
					date_from varchar2(10) path '@date_from',
					date_to varchar2(10) path '@date_to',
					stocks_xml xmltype path 'stocks'
			 ) x,
			 xmltable(
				'/stocks/stock'
				passing x.stocks_xml
				columns
					stock_id number path '@stock_id',
					orders_count number path '@orders_count',
					total_quantity number path '@total_quantity',
					total_amount varchar2(30) path '@total_amount',
					stock_description nvarchar2(100) path 'text()'
			 ) s
		where s.stock_description=p_stock_description
		order by rep.report_id,s.stock_id
	) loop
		dbms_output.put_line(
            '--'||
			'report_id='||r.report_id||
			', generated_at='||r.generated_at||
			', date_from='||r.date_from||
			', date_to='||r.date_to||
			', stock_id='||r.stock_id||
			', orders_count='||r.orders_count||
			', total_quantity='||r.total_quantity||
			', total_amount='||r.total_amount||
			', stock_description='||r.stock_description
		);
	end loop;
end;
/

declare
	v_report_id number;
begin
	insert_warehouse_report(
		p_date_from=>date '2023-01-01',
		p_date_to=>date '2026-01-31',
		p_report_id=>v_report_id
	);

	dbms_output.put_line('Inserted report_id='||v_report_id);
end;
/

select
	report_id,
	report_xml
from report;
/

select * from Stocks;
begin
	get_report_stock_by_description('Dry Goods Storage - Sector B');
end;
/



EXPLAIN PLAN FOR
SELECT r.report_id
FROM report r
WHERE XMLEXISTS(
  '/WarehouseReport/Orders/Order[@status="Created"]'
  PASSING r.report_xml
);

SELECT * 
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, NULL, 'BASIC +PREDICATE +ALIAS'));
/




begin
    execute immediate 'drop index report_xml_idx';
exception
    when others then
        if sqlcode != -1418 then -- ORA-01418: index does not exist
            raise;
        end if;
end;
/

SELECT table_name, column_name, storage_type
FROM user_xml_tab_cols
WHERE table_name = 'REPORT';

-- 2) Recreate REPORT with XML storage that supports XMLINDEX
BEGIN EXECUTE IMMEDIATE 'drop index report_xml_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'drop table report purge'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE report(
    report_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_xml XMLTYPE NOT NULL
)

XMLTYPE COLUMN report_xml STORE AS SECUREFILE CLOB;
/

-- (for newer DB versions you can use: STORE AS BINARY XML)

-- 3) Create XML index again
CREATE INDEX report_xml_idx
ON report(report_xml)
INDEXTYPE IS XDB.XMLINDEX;

