create table stocks(
    stock_id number generated by default as identity primary key,
    capacity number not null check(capacity>0),
    filled_part number default 0 not null,
    description nvarchar2(100) not null,
    constraint ck_stock_capacity check (filled_part<=capacity)
);

create table users(
    user_id number generated by default as identity primary key,
    email varchar2(255) not null unique,
    user_role varchar2(30) not null,
    password_hash raw(64) not null unique,
    created_at timestamp default current_timestamp,
    constraint ck_user_role check (user_role in ('Operator','Manager','Accountant','Admin'))
);

create table products(
    product_id number generated by default as identity primary key,
    stock_id number not null,
    name nvarchar2(200) not null,
    price number(19,4) default 0.0000 not null,
    quantity number default 0 not null check (quantity>=0),
    constraint fk_products_stocks foreign key (stock_id) references stocks(stock_id)
);

create table tasks(
    task_id number generated by default as identity primary key,
    user_id number not null,
    due_date timestamp not null,
    priority varchar2(30) not null check (priority in ('Low','Moderate','High','Highest')),
    description clob not null,
    is_completed number(1) default 0,
    constraint fk_tasks_users foreign key (user_id) references users(user_id)
);

create table orders(
    order_id number generated by default as identity primary key,
    order_date timestamp default current_timestamp not null,
    order_status varchar2(50) default 'Created' not null,
    total_amount number(19,4) default 0.0000,
    constraint ck_order_status check (order_status in ('Created','In work','Shipped','Canceled'))
);

create table order_items(
    item_id number generated by default as identity primary key,
    order_id number not null,
    product_id number not null,
    quantity number default 1 not null check (quantity > 0),
    constraint fk_orderitems_orders foreign key (order_id) references orders(order_id),
    constraint fk_orderitems_products foreign key (product_id) references products(product_id)
);

create table pack(
    pack_id number generated by default as identity primary key,
    user_id number not null,
    order_id number not null,
    pack_date timestamp default current_timestamp not null,
    pack_status varchar2(50) default 'Not packed',
    constraint fk_pack_users foreign key (user_id) references users(user_id),
    constraint fk_pack_orders foreign key (order_id) references orders(order_id),
    constraint ck_pack_status check (pack_status in ('Not packed','Packed','Shipped'))
);

create table pack_items(
    item_id number generated by default as identity primary key,
    pack_id number not null,
    product_id number not null,
    quantity number default 1 not null check (quantity > 0),
    unit_price number(19,4) not null check (unit_price >= 0),
    constraint fk_packitems_pack foreign key (pack_id) references pack(pack_id),
    constraint fk_packitems_products foreign key (product_id) references products(product_id)
);
