create table Stocks(
    Stock_ID number generated by default as identity primary key,
    Capacity number not null check(Capacity>0),
    Filled_part number default 0 not null,
    Description nvarchar2(100) not null,
    constraint CK_Stock_Capacity check (Filled_part<=Capacity)
);
create table Users(
    User_ID number generated by default as identity primary key,
    Email varchar2(255) not null unique,
    User_Role varchar2(30) not null,
    Password_hash raw(64) not  null unique,
    Created_at timestamp default current_timestamp,
    constraint CK_User_Role check (User_Role in ('Operator','Manager','Accountant','Admin'))
);

create table Products(
    Product_ID number generated by default as identity primary key,
    Stock_ID number not null,
    Name nvarchar2(200) not null,
    Price number(19,4) default 0.0000 not null,
    Quantity number default 0 not null check (Quantity>=0),
    constraint FK_Products_Stocks foreign key (Stock_ID) references Stocks(Stock_ID)
);

create table Tasks(
    Task_ID number generated by default as identity primary key,
    User_ID number not null,
    Due_date timestamp not null,
    Priority varchar2(30) not null check (Priority in ('Low','Moderate','High','Highest')),
    Description clob not null,
    Is_completed number(1) default 0,
    constraint FK_Tasks_Users foreign key (User_ID) references Users(User_ID)
);

create table Orders(
    Order_ID number generated by default as identity primary key,
    Order_date timestamp default current_timestamp not null,
    Order_status varchar2(50) default 'Created' not null,
    Total_amount number(19,4) default 0.0000,
    constraint CK_Order_Status check (Order_status in ('Created','In work','Shipped','Canceled'))
);

create table Order_items(
    Item_ID number generated by default as identity primary key,
    Order_ID NUMBER NOT NULL,
    Product_ID NUMBER NOT NULL,
    Quantity NUMBER DEFAULT 1 NOT NULL CHECK (Quantity > 0),
    CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID),
    CONSTRAINT FK_OrderItems_Products FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID)
);


create table Pack(
     Pack_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_ID NUMBER NOT NULL,
    Order_ID NUMBER NOT NULL,
    Pack_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Pack_status VARCHAR2(50) DEFAULT 'Not packed',
    CONSTRAINT FK_Pack_Users FOREIGN KEY (User_ID) REFERENCES Users(User_ID),
    CONSTRAINT FK_Pack_Orders FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID),
    CONSTRAINT CK_Pack_Status CHECK (Pack_status IN ('Not packed','Packed','Shipped'))
);

create table Pack_items(
    Item_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Pack_ID NUMBER NOT NULL,
    Product_ID NUMBER NOT NULL,
    Quantity NUMBER DEFAULT 1 NOT NULL CHECK (Quantity > 0),
    Unit_price NUMBER(19,4) NOT NULL CHECK (Unit_price >= 0),
    CONSTRAINT FK_PackItems_Pack FOREIGN KEY (Pack_ID) REFERENCES Pack(Pack_ID),
    CONSTRAINT FK_PackItems_Products FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID)
);