services:
  mssql_2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_2019
    entrypoint:
      - /bin/bash
      - /var/opt/mssql/entrypoint.sh
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!StrongPass123"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./mssql_data/db_init.sql:/var/opt/mssql/db_init.sql:ro
      - ./mssql_data/entrypoint.sh:/var/opt/mssql/entrypoint.sh:ro
    networks:
      - tdwa_net

  nginx_tcp:
    image: nginx:alpine
    container_name: nginx_tcp
    depends_on:
      - mssql_2019
    ports:
      - "1444:1444"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - tdwa_net

  tdwa07:
    image: manmadee/tdwa07-01:latest
    container_name: tdwa07
    depends_on:
      - nginx_tcp
    environment:
      CONNECTION_STRING: "Server=nginx_tcp,1444;Database=Celebrities;User Id=sa;Password=!StrongPass123;Encrypt=True;TrustServerCertificate=True;"
    ports:
      - "3000:3000"
    networks:
      - tdwa_net

networks:
  tdwa_net:
    driver: bridge

volumes:
  mssql_data:
