user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    server {
        listen 1444;
        proxy_pass mssql_2019:1433;
    }
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
}
