create table product_files(
	file_id number generated by default as identity primary key,
	product_name varchar2(200) not null,
	foto blob,
	doc_pdf bfile
)
lob(foto) store as securefile foto_lob(
	tablespace lob_data
);


--loading a .pdf document
insert into product_files(product_name,foto,doc_pdf)
values(
	'product 1',
	empty_blob(),
	bfilename('LOB_DOC_DIR','Lab_10.pdf')
);




--loading a photo

declare
	v_blob blob;
	v_bfile bfile:=bfilename('LOB_PHOTO_DIR','Logo.jpg');
begin
	update product_files
	set foto=empty_blob()
	where file_id=1
	returning foto into v_blob;

	dbms_lob.fileopen(v_bfile,dbms_lob.file_readonly);
	dbms_lob.loadfromfile(
		dest_lob => v_blob,
		src_lob  => v_bfile,
		amount   => dbms_lob.getlength(v_bfile)
	);
	dbms_lob.fileclose(v_bfile);

	commit;
end;
/


--quick check

select
	file_id,
	product_name,
	dbms_lob.getlength(foto) as foto_size,
    dbms_lob.getlength(doc_pdf) as doc_size
from product_files;



select file_id,foto
from product_files
where file_id=1;

select file_id,doc_pdf
from product_files
where file_id=1;


