--FOR EXPORT

create or replace type warehouse_period_row_t as object(
	order_id number,
	order_date date,
	product_id number,
	product_name varchar2(200),
	stock_id number,
	stock_description varchar2(100),
	unit_price number(19,4),
	product_quantity number,
	line_amount number(19,4)
);
/

create or replace type warehouse_period_tab_t as table of warehouse_period_row_t;
/

create or replace function fn_warehouse_period_data(
	p_date_from date,
	p_date_to date
) return warehouse_period_tab_t pipelined
as
begin
	for r in(
		select
			o.order_id,
			trunc(o.order_date) as order_date,
			p.product_id,
			p.name as product_name,
			s.stock_id,
			s.description as stock_description,
			p.price as unit_price,
			oi.quantity as product_quantity,
			round(oi.quantity*p.price,4) as line_amount
		from orders o
		join order_items oi on oi.order_id=o.order_id
		join products p on p.product_id=oi.product_id
		join stocks s on s.stock_id=p.stock_id
		where o.order_date>=p_date_from
		and o.order_date<p_date_to+1
		order by o.order_date,p.product_id
	) loop
		pipe row(
			warehouse_period_row_t(
				r.order_id,
				r.order_date,
				r.product_id,
				r.product_name,
				r.stock_id,
				r.stock_description,
				r.unit_price,
				r.product_quantity,
				r.line_amount
			)
		);
	end loop;

	return;
end;
/

select *
from table(fn_warehouse_period_data(date '2023-01-01',date '2026-01-31'));
/

--FOR IMPORT

create table warehouse_import_data(
	import_id number generated by default as identity primary key,
	product_name varchar2(200) not null,
	stock_description varchar2(100) not null,
	unit_price number(19,1) not null,
	product_quantity number(10,1) not null,
	load_date date not null
);
/
select *
from warehouse_import_data
order by import_id;
/
