
CREATE TABLE report (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_xml XMLTYPE NOT NULL
);
/

select * from report;

------------------------------------------------------------
-- 2) Процедура генерации XML
--    (orders + order_items + products + stocks, итоги и timestamp)
------------------------------------------------------------
CREATE OR REPLACE PROCEDURE usp_generate_warehouse_report_xml (
    p_report_xml OUT XMLTYPE
) AS
BEGIN
    SELECT
        XMLELEMENT(
            "WarehouseReport",
            XMLATTRIBUTES(
                TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZH:TZM') AS "generatedAt"
            ),

            -- GlobalTotals
            (
                SELECT XMLELEMENT(
                           "GlobalTotals",
                           XMLELEMENT("TotalOrders", COUNT(DISTINCT o.order_id)),
                           XMLELEMENT("TotalAmountByOrdersTable", NVL(SUM(o.total_amount), 0)),
                           XMLELEMENT("CalculatedTotalByItems", NVL(SUM(oi.quantity * p.price), 0)),
                           XMLELEMENT("TotalUnits", NVL(SUM(oi.quantity), 0))
                       )
                FROM orders o
                LEFT JOIN order_items oi ON oi.order_id = o.order_id
                LEFT JOIN products p     ON p.product_id = oi.product_id
            ),

            -- StatusSubtotals
            (
                SELECT XMLELEMENT(
                           "StatusSubtotals",
                           XMLAGG(
                               XMLELEMENT(
                                   "StatusSubtotal",
                                   XMLATTRIBUTES(s.order_status AS "status"),
                                   XMLELEMENT("OrdersCount", s.orders_count),
                                   XMLELEMENT("StatusAmount", s.status_amount)
                               )
                               ORDER BY s.order_status
                           )
                       )
                FROM (
                    SELECT
                        o.order_status,
                        COUNT(*) AS orders_count,
                        NVL(SUM(o.total_amount), 0) AS status_amount
                    FROM orders o
                    GROUP BY o.order_status
                ) s
            ),

            -- Orders
            (
                SELECT XMLELEMENT(
                           "Orders",
                           XMLAGG(
                               XMLELEMENT(
                                   "Order",
                                   XMLATTRIBUTES(
                                       o.order_id AS "id",
                                       TO_CHAR(o.order_date, 'YYYY-MM-DD"T"HH24:MI:SS') AS "orderDate",
                                       o.order_status AS "status"
                                   ),

                                   -- OrderTotals
                                   (
                                       SELECT XMLELEMENT(
                                                  "OrderTotals",
                                                  XMLELEMENT("UnitsInOrder", NVL(SUM(oi2.quantity), 0)),
                                                  XMLELEMENT("OrderSubtotal", NVL(SUM(oi2.quantity * p2.price), 0))
                                              )
                                       FROM order_items oi2
                                       JOIN products p2 ON p2.product_id = oi2.product_id
                                       WHERE oi2.order_id = o.order_id
                                   ),

                                   -- Items
                                   (
                                       SELECT XMLELEMENT(
                                                  "Items",
                                                  XMLAGG(
                                                      XMLELEMENT(
                                                          "Item",
                                                          XMLATTRIBUTES(oi3.item_id AS "id"),
                                                          XMLELEMENT("Quantity", oi3.quantity),
                                                          XMLELEMENT(
                                                              "Product",
                                                              XMLATTRIBUTES(p3.product_id AS "id"),
                                                              XMLELEMENT("Name", p3.name),
                                                              XMLELEMENT("Price", p3.price)
                                                          ),
                                                          XMLELEMENT(
                                                              "Stock",
                                                              XMLATTRIBUTES(s3.stock_id AS "id"),
                                                              XMLELEMENT("Description", s3.description)
                                                          )
                                                      )
                                                      ORDER BY oi3.item_id
                                                  )
                                              )
                                       FROM order_items oi3
                                       JOIN products p3 ON p3.product_id = oi3.product_id
                                       JOIN stocks   s3 ON s3.stock_id   = p3.stock_id
                                       WHERE oi3.order_id = o.order_id
                                   )
                               )
                               ORDER BY o.order_id
                           )
                       )
                FROM orders o
            )
        )
    INTO p_report_xml
    FROM dual;
END;
/
SHOW ERRORS

------------------------------------------------------------
-- 3) Процедура вставки XML в Report
------------------------------------------------------------
CREATE OR REPLACE PROCEDURE usp_insert_warehouse_report (
    p_inserted_report_id OUT NUMBER
) AS
    v_xml XMLTYPE;
BEGIN
    usp_generate_warehouse_report_xml(v_xml);

    INSERT INTO report (report_xml)
    VALUES (v_xml)
    RETURNING report_id INTO p_inserted_report_id;
END;
/
SHOW ERRORS

------------------------------------------------------------
-- 4) XML-индекс на XML-столбец
------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX ix_report_xml';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN -- ORA-01418: specified index does not exist
            RAISE;
        END IF;
END;
/

CREATE INDEX ix_report_xml
ON report(report_xml)
INDEXTYPE IS XDB.XMLINDEX;
/

------------------------------------------------------------
-- 5) Процедура извлечения атрибутов/элементов из XML
--    Параметр: значение атрибута Order/@status ИЛИ элемента Product/Name
------------------------------------------------------------
CREATE OR REPLACE PROCEDURE usp_find_in_report_xml (
    p_search_value IN  NVARCHAR2,
    p_result       OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_result FOR
        WITH attr_matches AS (
            SELECT
                r.id AS report_id,
                x.order_id,
                x.order_status,
                CAST(NULL AS NVARCHAR2(200)) AS product_name,
                'Order/@status' AS matched_in
            FROM report r
            CROSS JOIN XMLTABLE(
                '/WarehouseReport/Orders/Order'
                PASSING r.report_xml
                COLUMNS
                    order_id     NUMBER        PATH '@id',
                    order_status VARCHAR2(50)  PATH '@status'
            ) x
            WHERE x.order_status = p_search_value
        ),
        elem_matches AS (
            SELECT
                r.id AS report_id,
                o.order_id,
                o.order_status,
                i.product_name,
                'Product/Name' AS matched_in
            FROM report r
            CROSS JOIN XMLTABLE(
                '/WarehouseReport/Orders/Order'
                PASSING r.report_xml
                COLUMNS
                    order_id     NUMBER        PATH '@id',
                    order_status VARCHAR2(50)  PATH '@status',
                    items_xml    XMLTYPE       PATH 'Items'
            ) o
            CROSS JOIN XMLTABLE(
                '/Items/Item'
                PASSING o.items_xml
                COLUMNS
                    product_name NVARCHAR2(200) PATH 'Product/Name/text()'
            ) i
            WHERE i.product_name = p_search_value
        )
        SELECT *
        FROM attr_matches
        UNION ALL
        SELECT *
        FROM elem_matches
        ORDER BY report_id, order_id, matched_in;
END;
/
SHOW ERRORS

------------------------------------------------------------
-- Примеры вызова
------------------------------------------------------------
DECLARE
    v_id NUMBER;
BEGIN
    usp_insert_warehouse_report(v_id);
    DBMS_OUTPUT.PUT_LINE('Inserted report id = ' || v_id);
END;
/

VARIABLE rc REFCURSOR;

EXEC usp_find_in_report_xml(N'Created', :rc);
PRINT rc;

EXEC usp_find_in_report_xml(N'Product 20080', :rc);
PRINT rc;